### ISSUE TITLE
AWS environment variable passthrough inconsistent with documentation

### ISSUE THREAD

**Issue by ttung** [nextstrain/cli#103]
**Current Behavior**  
AWS environment variables are passed from the person who runs `nextstrain build --aws-batch` to the batch job.  This is inconsistent with the documentation, which [suggests](https://docs.nextstrain.org/projects/cli/en/latest/aws-batch/#roles) that the job assumes the role.

**Possible solution**  
Revert https://github.com/nextstrain/cli/commit/7c47212e806b6817c264a7327a2787434a612969

**Comment by tsibley** [comment]
@ttung Ah, apologies that the documentation misled.

To clarify: the role in the Batch job definition is used if no other credentials are provided. Credentials may be provided to the job via local environment variables, on the principle that remote builds aim to behave similarly to local builds. 

In terms of reverting 7c47212, while I'd like to eventually pass local credentials a different way (outside of the environment), I think we do want to be able to pass them. It could be made optional, however. Not sure which way the default should go, but I'd be inclined to keep it default to passing.

**Comment by tsibley** [comment]
I added some hopefully clarifying language to the doc in f15b0a9. Please let me know if this reads clearly to you or if it could stand for some more tweaks.

**Comment by ttung** [comment]
How does one launch an AWS batch job without environmental credentials defined?  From `~/.aws/profile`?

**Comment by tsibley** [comment]
@ttung Yep, you can use `~/.aws/credentials` (or even `~/.aws/config`) by default. [A short example](https://github.com/nextstrain/cli/blob/master/doc/aws-batch.md#aws-credentials) with links to more details in AWS' doc. (Links were slightly broken, but I've just fixed them up.)
