### ISSUE TITLE
Invalid option --output-strains for augur filter in latest Nextstrain update

### ISSUE THREAD

**Issue by ArnieBerg** [nextstrain/cli#119]
I cloned the latest ncov of Nextstrain (3.0.3) from github (running the CLI environment in conda, Ubuntu) and when I run the snakefile for any example profile, I get to an 'augur filter' step that reports that the option '--output-strains' is invalid.  When I check 'augur filter -h', sure enough, there is no '--output-strains' option listed.

Maybe I need to update the Nextstrain conda package?  After much difficulty I got the latest version installed but it made no difference.  Has this broken?

**Comment by jameshadfield** [comment]
What version of augur are you running @ArnieBerg? This functionality was released in augur v11.2.0 (via [this commit](https://github.com/nextstrain/augur/commit/f80ae36ed1c29ed6426de3e19b9be8a491e4b3ce)). Working out what version of augur you are using is somewhat connected to how you are running the workflow -- are you running `snakemake` itself, `nextstrain build` or `snakemake --use-conda` (or something else)?

**Comment by ArnieBerg** [comment]
Further information....I am running this in a WSL environment on a Windows machine, so I created a new Ubuntu distro, installed conda and then installed Nextstrain.  This instance gave me a version 12.0 for augur.

In the original Ubuntu distro, I was unable to successfully update Nextstrain.  I could not remove it through conda.  I deleted the Nextstrain environment and re-installed it, but it would not give me augur 12.0.

This ticket can be closed.

**Comment by jameshadfield** [comment]
Sorry to hear about these troubles @ArnieBerg.

In terms of the nCoV repo we are maintaining [a conda environment](https://github.com/nextstrain/ncov/blob/master/workflow/envs/nextstrain.yaml) which enforce that the rules use the correct versions of dependencies (augur, mafft etc etc). If you run your build via `snakemake --use-conda --cores 4 --profile ./my_profiles/example  -p` it should 🤞 just work. In the case which you update the nCoV repo, then the conda environment snakemake uses will also update as needed. cc @huddlej 

Let us know if there are any other issues!
