### ISSUE TITLE
nextstrain check-setup --set-default fails because it does not find /sys/fs/cgroup/memory/memory.limit_in_bytes

### ISSUE THREAD

**Issue by txwikinger** [nextstrain/cli#135]
**Current Behavior**  
nextstrain check-setup --set-default fails

This happens since cgroups has changed some files inside /sys/fs/cgroups, memeory/memory.limit_in_bytes does not exist anymore and this makes the script fail with stackstrace.

**Expected behavior**  
nextstrain check-setup --set-defaults should be able to finish without error message of missing file

**How to reproduce**  
Steps to reproduce the current behavior:  
1) In terminal run "nextstrain check-setup --set-default"

Output:

```
nextstrain-cli is up to date!

Testing your setup…
cat: /sys/fs/cgroup/memory/memory.limit_in_bytes: No such file or directory
Traceback (most recent call last):
  File "/home/raj/miniconda3/envs/nextstrain/bin/nextstrain", line 8, in <module>
    sys.exit(main())
  File "/home/raj/miniconda3/envs/nextstrain/lib/python3.9/site-packages/nextstrain/cli/__main__.py", line 10, in main
    return cli.run( argv[1:] )
  File "/home/raj/miniconda3/envs/nextstrain/lib/python3.9/site-packages/nextstrain/cli/__init__.py", line 31, in run
    return opts.__command__.run(opts)
  File "/home/raj/miniconda3/envs/nextstrain/lib/python3.9/site-packages/nextstrain/cli/command/check_setup.py", line 63, in run
    runner_tests = [
  File "/home/raj/miniconda3/envs/nextstrain/lib/python3.9/site-packages/nextstrain/cli/command/check_setup.py", line 64, in <listcomp>
    (runner, runner.test_setup())
  File "/home/raj/miniconda3/envs/nextstrain/lib/python3.9/site-packages/nextstrain/cli/runner/docker.py", line 206, in test_setup
    *test_memory_limit(),
  File "/home/raj/miniconda3/envs/nextstrain/lib/python3.9/site-packages/nextstrain/cli/runner/docker.py", line 147, in test_memory_limit
    total, cgroup = map(int, run_bash(report_memory))
  File "/home/raj/miniconda3/envs/nextstrain/lib/python3.9/site-packages/nextstrain/cli/runner/docker.py", line 440, in run_bash
    return capture_output([
  File "/home/raj/miniconda3/envs/nextstrain/lib/python3.9/site-packages/nextstrain/cli/util.py", line 116, in capture_output
    result = subprocess.run(
  File "/home/raj/miniconda3/envs/nextstrain/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['docker', 'run', '--rm', 'nextstrain/base:build-20211120T003711Z', 'bash', '-c', "\n                awk '/^MemTotal:/ { print $2 * 1024 }' /proc/meminfo\n                cat /sys/fs/cgroup/memory/memory.limit_in_bytes\n            "]' returned non-zero exit status 1.
```

**Possible solution**  
In general this should be decouplked from changes within cgroup. It is not a good practice to use files directly that are not guaranteed to not change. This also makes it difficult to support multiple versions of cgroup. Ideally, a more stable API should be used.

Alternatively, it should detect the cgroup version and use the correct file relevant to the version

**Your environment: if browsing Nextstrain online**  
 - Operating system:  
 - Browser:  

**Your environment: if running Nextstrain locally**  
 - Operating system:   Linux Manajaro 
 - Browser:  N/A
 - Version (e.g. `auspice 2.7.0`):  
 -  Linux kernel 5.10.79-1-MANJARO x86_64
 -  cgroups: v2

**Additional context**

**Comment by tsibley** [comment]
Thanks for reporting this @txwikinger.

Do you have a recommendation for a "more stable API" than the cgroup interface files? This was the best method I could find for introspecting the externally-placed memory constraints on a container.

As a straightforward fix, it seems enough to try to read both the cgroup v1 and v2 files and use whichever works. Based on what I read in the [cgroup v2 documentation](https://www.kernel.org/doc/html/latest/admin-guide/cgroup-v2.html), it looks like we'd want to look for `/sys/fs/cgroup/memory.max` for v2.

**Comment by huddlej** [comment]
I don't have a suggestion for a fix, but I wanted to report that I also experienced this error a couple of days ago.

**Comment by tsibley** [comment]
@huddlej Can you share more context about the environment in which you saw this? I know it needs fixing, but I'm not sure how widely cgroups v2 is in use (in particular amongst our users).

**Comment by huddlej** [comment]
This error happens on my work machine which is several versions behind on OS and Docker. Here are the specs:

 - Mac OS 10.14.6
 - Docker Desktop 4.4.2
 - Python 3.8.10 (via Miniconda3)
 - Nextstrain CLI 3.0.6

I'm going to try updating Docker to 4.5.0 and will report back (looks like I need to restart and maybe my Docker install is broken :().

**Comment by tsibley** [comment]
> The contents of this file just says `max`, though.

Hmm. While I have you here, could you try running this inside a `nextstrain shell`?

```
find /sys/fs/cgroup/ -iname 'memory*' | while read -r fname; do
  echo "# $fname";
  cat "$fname";
done
```

**Comment by tsibley** [comment]
Also, what's your `uname -a` inside the `nextstrain shell`?

**Comment by joverlee521** [comment]
I also ran into this error with the same environment as @huddlej
```shell
nextstrain:/nextstrain/build $ find /sys/fs/cgroup/ -iname 'memory*' | while read -r fname; do
>   echo "# $fname";
>   cat "$fname";
> done
# /sys/fs/cgroup/memory.events
low 0
high 0
max 0
oom 0
oom_kill 0
# /sys/fs/cgroup/memory.events.local
low 0
high 0
max 0
oom 0
oom_kill 0
# /sys/fs/cgroup/memory.swap.current
0
# /sys/fs/cgroup/memory.swap.max
max
# /sys/fs/cgroup/memory.swap.events
high 0
max 0
fail 0
# /sys/fs/cgroup/memory.current
2785280
# /sys/fs/cgroup/memory.stat
anon 811008
file 1081344
kernel_stack 49152
percpu 0
sock 0
shmem 0
file_mapped 0
file_dirty 0
file_writeback 0
anon_thp 0
inactive_anon 811008
active_anon 0
inactive_file 946176
active_file 135168
unevictable 0
slab_reclaimable 131128
slab_unreclaimable 262424
slab 393552
workingset_refault_anon 0
workingset_refault_file 0
workingset_activate_anon 0
workingset_activate_file 0
workingset_restore_anon 0
workingset_restore_file 0
workingset_nodereclaim 0
pgfault 2871
pgmajfault 0
pgrefill 0
pgscan 0
pgsteal 0
pgactivate 33
pgdeactivate 0
pglazyfree 0
pglazyfreed 0
thp_fault_alloc 0
thp_collapse_alloc 0
# /sys/fs/cgroup/memory.low
0
# /sys/fs/cgroup/memory.swap.high
max
# /sys/fs/cgroup/memory.min
0
# /sys/fs/cgroup/memory.oom.group
0
# /sys/fs/cgroup/memory.max
max
# /sys/fs/cgroup/memory.high
max
```
```shell
nextstrain:/nextstrain/build $ uname -a
Linux 0a270612c124 5.10.76-linuxkit #1 SMP Mon Nov 8 10:21:19 UTC 2021 x86_64 GNU/Linux
```

**Comment by tsibley** [comment]
Thanks @joverlee521! That's super helpful to see. No useful values there, unfortunately. `max` means the container is allowed the whole container host memory, but the container host on macOS/Windows is a VM, which _does_ have limits (that should be found by the existing `/proc/meminfo` read). My plan:

- [ ] Fix existing check for cgroups v1 file to fail gracefully when run on a v2 system
- [ ] Extend check to support cgroups v2 when possible (e.g. when `memory.max` has a value that's not `max`).

With some tinkering, I also figured out how to investigate this myself. For posterity and my own reference:

Launch a late model Ubuntu version in a VM, for access to cgroups v2:

```
multipass launch -n foo 22.04
multipass shell foo
```

Install Docker inside it:

```
sudo apt install docker.io
sudo gpasswd -a $USER docker
exec sudo -iu $USER
```

Then launch Docker containers and inspect the cgroups v2 files available within them (which will be different than the cgroups v2 files available within the host VM).

```console
$ docker run --rm -it --memory 2gib ubuntu:20.04 cat /sys/fs/cgroup/memory.max
2147483648
$ docker run --rm -it ubuntu:20.04 cat /sys/fs/cgroup/memory.max
max
```

**Comment by tsibley** [comment]
@joverlee521 @huddlej @txwikinger If you could test that PR #153 addresses this issue for you, I'd appreciate it! I believe it should based on my own testing. You can install that PR into an isolated/throwaway Python environment with:

```
python3 -m venv /tmp/cli-pr-153
source /tmp/cli-pr-153/bin/activate
python3 -m pip install --upgrade pip setuptools wheel
python3 -m pip install 'nextstrain-cli @ https://github.com/nextstrain/cli/archive/trs/cgroups-v2.zip'
```
