### ISSUE TITLE
Fix Bioconda recipe

### ISSUE THREAD

**Issue by huddlej** [nextstrain/cli#139]
## Description
[The last two Bioconda package auto-bumps from PyPI failed to build due to missing dependencies](https://github.com/bioconda/bioconda-recipes/pull/31373). We need to update the dependencies in the Bioconda recipe to match `setup.py` and bump to the latest version.

[This issue is blocking improvements to the Nextstrain installation docs](https://github.com/nextstrain/docs.nextstrain.org/pull/83).

**Comment by huddlej** [comment]
@tsibley Even with your extensive notes in the code comments, issues, and PRs, I'm not 100% sure I get the extent of the s3fs/boto* dependencies issues. I did try to update the Bioconda recipe to match [the s3fs version pinned for PyPI](https://github.com/nextstrain/cli/blob/77c97bfecaf3dda84a8c20c343afc70cc6659f53/setup.py#L110), but this caused Conda to somehow "resolve" the dependencies by dropping boto3 from the Conda environment (despite its explicit inclusion in the recipe). When I removed the s3fs version pin, the environment actually resolved and the tests ran as expected. [The s3fs version that Conda installed was 0.4.2](https://dev.azure.com/bioconda/bioconda-recipes/_build/results?buildId=8937&view=logs&j=e14e69ff-a0ae-55c4-b71d-229b239cfb2f&t=7df82132-b284-504b-53d6-7d3e63519572&l=441), though, suggesting that the dependency hell exists in the Conda recipes, too.

Once the updated Bioconda recipe is approved and merged, I'll test on different OSs and Pythons to confirm everything is still working as expected with this older s3fs version.

**Comment by huddlej** [comment]
Fixed by https://github.com/bioconda/bioconda-recipes/pull/32149

**Comment by tsibley** [comment]
@huddlej 

> Even with your extensive notes in the code comments, issues, and PRs, I'm not 100% sure I get the extent of the s3fs/boto* dependencies issues.

Yep, it's a giant mess that's quite hard to grok. I _think_ your update to https://github.com/bioconda/bioconda-recipes/pull/32149 is reasonable and probably correct. However, I'm not sure without testing if s3fs 0.4.2 will avoid [this bug](https://github.com/nextstrain/cli/commit/e9a9aa6c2ff9b9ab6659982689c9b899d3addd8b) with whatever version of aiobotocore/botocore gets installed by Conda.

**Comment by tsibley** [comment]
Ahh, s3fs 0.4.2 may be ok as it is the last version not to depend on aiobotocore.
