### ISSUE TITLE
Conda install with Python 3.6 is unusable with `--aws-batch`

### ISSUE THREAD

**Issue by victorlin** [nextstrain/cli#148]
**Current Behavior**  

Creating a `conda` environment with `nextstrain-cli` and `python=3.6` results in an environment where `--aws-batch` is unusable.

**Expected behavior**  

Environment should work.

**How to reproduce**  
Steps to reproduce the current behavior:  
1. `conda create -n test -c conda-forge -c bioconda nextstrain-cli python=3.6`

    Output:

    ```
    The following NEW packages will be INSTALLED:

    boto3              conda-forge/osx-64::boto3-1.5.11-py36_0
    botocore           conda-forge/osx-64::botocore-1.5.92-py36_0
    ...
    nextstrain-cli     bioconda/noarch::nextstrain-cli-3.0.6-pyhdfd78af_0
    ...
    python             conda-forge/osx-64::python-3.6.15-haf480d7_0_cpython
    ...
    s3fs               conda-forge/osx-64::s3fs-0.1.2-py36_0
    ...
    ```
2. Run `nextstrain build --aws-batch ...`

    Output:

    ```
        ...
        config = Config(retries = {'max_attempts': 3})
        ...
    TypeError: Got unexpected keyword argument 'retries'
    ```

3. Fix above error by upgrading `boto3` to the [version where this feature was added](https://github.com/boto/botocore/blob/develop/CHANGELOG.rst#160): `conda install boto3=1.6.0`
4. Run `nextstrain build --aws-batch ...`

    Output:

    ```
        ...
        optionss = list(map(cls._get_kwargs_from_urls, urlpath))
        ...
    AttributeError: type object 'S3FileSystem' has no attribute '_get_kwargs_from_urls'
    ```

5. Fix above error by upgrading `s3fs` to a [compatible version](https://github.com/dask/dask/issues/5152#issuecomment-530104690): `conda install s3fs=0.3`
6. Run `nextstrain build --aws-batch ...`. Now it will finally work.

Other setups that install the correct versions of `boto3` and `s3fs`:

1. `mamba create -n test -c conda-forge -c bioconda nextstrain-cli python=3.6`
2. `conda create -n test -c conda-forge -c bioconda nextstrain-cli python=3.7`

**Possible solutions**  

1. Set minimum Python version to 3.7
2. Set minimum `boto3` and `s3fs` versions in and [bioconda recipe](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/nextstrain-cli/meta.yaml).

**Your environment: if running Nextstrain locally**  
 - Operating system: macOS 11.6.1

**Comment by tsibley** [comment]
Ugh, this thorny dep issue again, in a slightly new variation. I seem to recall @huddlej ran into this precise issue with Conda vs. Mamba a little while back and we discussed it somewhere (Slack? GitHub?), but I don't recall the venue or conclusion. Will have to try to find it.

**Comment by tsibley** [comment]
```
conda create -p /tmp/ns -c conda-forge -c bioconda --override-channels --strict-channel-priority nextstrain-cli python=3.6
```

works at this point in time, and though I don't know if the `--override-channels` and `--strict-channel-priority` make a functional difference in this case, they're suggested practice.

In any case, this issue is also largely moot due to time's march forward and Python 3.6 being less of a going concern.
