### ISSUE TITLE
ENH: Link to relevant PRs in changelog

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/cli#205]
### Context
I had a look at the changelog to see if a bug I got was fixed in a new version, but based from changelog alone I couldn't figure out if something was fixed or not. I then wanted to check the code for the entry in the changelog but noticed no PR was linked.

### Description
It could be helpful to link to PRs in the changelog so one can inspect the relevant code without having to go hunt in commits.

### Examples
https://github.com/nextstrain/cli/releases 4.1.0 and 4.1.1 don't reference any PRs or issues

### Possible solution
Manually add relevant PRs and/or issues when creating the changelog

@tsibley 

PS: Not sure if this should maybe be DOC instead

**Comment by tsibley** [comment]
Ah, yeah, this is useful to do. I used to ([one example](https://github.com/nextstrain/cli/blob/master/CHANGES.md#324-6-april-2022)), but fell off the wagon. So it's more just remembering to do it. Having recent releases with this practice visible when writing unreleased changelog entries is, for me, the best reminder to do it (e.g. reminder by example), so I'll try to get it going again with the next release.

Closing this as I don't think there's anything to track here (but re-open if you don't agree).

> PS: Not sure if this should maybe be DOC instead

We don't use those category prefixes in this repo, so doesn't really matter.
