### ISSUE TITLE
RFD: `remote upload`'s use of filenames

### ISSUE THREAD

**Issue by tsibley** [nextstrain/cli#221]
_Trying out an issue as a Request For Discussion (RFD) instead of doing it in a private Slack thread. I'll try to keep the issue description neutral and descriptive and updated with decisions, while putting my own opinions in the comments. -trs_

Let `x.json` and `y.json` be dataset JSONs, the _invocation_ column the parameter part of an `nextstrain remote upload` invocation, and the _result_ column be the paths of the final nextstrain.org URLs.

Current behaviour:

invocation                       | prefix?   | n? | filename used?           | result
----------------------------- | --------- | -- | ------------------------ | -------------------------------------
groups/test/a/b x.json        | yes (a/b) | 1  | no  (prefix)             | groups/test/a/b
groups/test/a/b x.json y.json | yes (a/b) | 2+ | yes (prefix + filename)  | groups/test/a/b/x groups/test/a/b/y
groups/test x.json            | no        | 1  | yes (filename)           | groups/test/x
groups/test x.json y.json     | no        | 2+ | yes (filename)           | groups/test/x groups/test/y

The first condition is "single" mode.

There's been a fair bit of past discussion over if this is the "right" behaviour, including:

- https://github.com/nextstrain/cli/pull/141#discussion_r804230300
- https://github.com/nextstrain/cli/issues/169
- [my scattered personal notes](https://github.com/tsibley/blab-standup/blob/master/2021-08-17.md#17-august-2021)
- Slack threads (links TK?)

(but I'm not sure if it's worth revisiting all those, so don't necessarily bother. It's ok if here now we cover the same ground again with fresh eyes.)

Things we might do different (some mutually exclusive, some not):

1. Add an option to use the filename when only a single resource is specified with a prefix (i.e. overriding "single" mode), e.g.  `--destination-from-filename` or something.

2. Default to always using the filename, even in what's currently "single" mode, and then provide an option to *not* use filenames, e.g.  `--ignore-filenames`.  This option would be compatible only with "single" mode, and thus could even be called `--single`. 

3. Default to never using the filename which effectively restricts the command to "single" mode, but then provide a `--multiple` or `--destination-from-filename` option to opt-into using the filenames and permit "multiple" mode.

4. ??? (maybe you have ideas)

Note that 2 and 3 are backwards incompatible with current behaviour (which is in use) and would probably be a surprising change.

Note also that both 2 and 3 would help with glob safety, as under `--single` (explicit in 2 or implicit in 3) if multiple datasets are detected, an error would be thrown.  That said, we could implement `--single` as an assertion-only option without changing the default behaviour.

**Comment by tsibley** [comment]
I'm a bit biased as I implemented the current behaviour (after some hemming and hawing and feeling different behaviours out), so it more-or-less represents what I think is "best". But I'm open to reasons to do something else!

Out of things 1 to 3 we might do different, I think today I'd implement 1 but skip 2 and 3.

I think 2 is less friendly to basic usage, particularly for folks starting off. It's easiest to explain, single-dataset uploads are probably the most common case for many users, and you could go far using _only_ the "single mode" invocation form.

3 is tempting with the benefit of hindsight because of the glob safety aspect, but feels probably not worth it given it'd be a breaking change. But maybe we shouldn't fret about that now and do it for a better future foundation when usage is higher.

**Comment by emmahodcroft** [comment]
I don't think I have strong feelings here, but I am also not 100% sure if I'm completely understanding, as I think I've always used upload in a very basic way. If I was to upload `groups/test a_b_x.json` does this comes out as `groups/test/a/b/x` ? This is the format I use a lot, but I've never considered how the files are stored (or if this matters). Would this be the same as uploading `groups/test/a/b x.json` with the proposed new filename option? (I think the URL would be the same but does it make any difference how files are stored internally - and does it matter?)

Sorry if this is a little away from the main question -- as I said, I don't think I have strong feelings so if this is distracting then I'm happy to go with what others think is best, with my ever-present caveat that changing default behaviours may be disruptive to users (but I don't think that's being proposed here).

**Comment by tsibley** [comment]
@emmahodcroft 

> If I was to upload `groups/test a_b_x.json` does this comes out as `groups/test/a/b/x` ? This is the format I use a lot, but I've never considered how the files are stored (or if this matters).

Correct. Your example is a case of the third row in the table above.

In the table, if the _Filename used?_ column says "yes", then the file's name is used by taking the basename (`a_b_x` in your example) and replacing underscores with slashes (to get `a/b/x`).

(How the files are stored remotely doesn't matter here, though how files are stored _locally_ does when the _Filename used?_ column says "yes".)

> Would this be the same as uploading `groups/test/a/b x.json` with the proposed new filename option? (I think the URL would be the same but does it make any difference how files are stored internally - and does it matter?)

Correct. This example is a case of the first row in the table above (to be super clear for those following along).

Current behaviour has this example ending up as `groups/test/a/b` and not `groups/test/a/b/x`. In potential solution (1) with a new option like ` --destination-from-filename`, the behaviour would switch to `groups/test/a/b/x`.

(Names in remote storage don't matter here either.)

> Sorry if this is a little away from the main question -- as I said, I don't think I have strong feelings so if this is distracting then I'm happy to go with what others think is best, with my ever-present caveat that changing default behaviours may be disruptive to users (but I don't think that's being proposed here).

Thanks for your input! It's valuable to hear that you mostly do `groups/test a_b_x.json`. I agree that changing defaults is disruptive and best avoided when possible.

**Comment by emmahodcroft** [comment]
Thank you for this great explanation @tsibley ! This really clarifies things for me and I appreciate you taking the time for it!

Though I don't have strong feelings, I think I'd agree that having an option like solution (1) might be nice and useful. Others may be able to offer more insightful feedback than that!

**Comment by jameshadfield** [comment]
Thanks for writing this up Tom. I don't think I'll remember the subtleties of single dataset upload vs multi and what happens to filenames no matter which option we choose, but my uncertainty felt here is no different to when using `aws s3 cp` or other tools. In all cases I rely on `--dry-run`, and for nextstrain-cli this is particularly good. That is to say, I don't think it's worth introducing backwards incompatible changes. We could add `--destination-from-filename` but in practice I think I'd end up using `groups/test/a/b/x x.json` instead.

I realise this RFC is focused on upload, but I do think consistency between upload + download is an important consideration in all of this (discussed in https://github.com/nextstrain/cli/issues/169#issue-1194056664).

**Comment by tsibley** [comment]
> In all cases I rely on `--dry-run`, and for nextstrain-cli this is particularly good. That is to say, I don't think it's worth introducing backwards incompatible changes. We could add `--destination-from-filename` but in practice I think I'd end up using `groups/test/a/b/x x.json` instead.

Ok, that's a super good perspective! I like not breaking compat now and leaving ourselves the option to add an option later.

> I realise this RFC is focused on upload, but I do think consistency between upload + download is an important consideration in all of this (discussed in [#169 (comment)](https://github.com/nextstrain/cli/issues/169#issue-1194056664)).

Agreed! Thanks for mentioning that. [The download behaviour is changing in the next release](https://github.com/nextstrain/cli/blob/2216314e6dd378c637c6f43f023afd4b7f4efb13/CHANGES.md#improvements), and I think makes the existing upload behaviour better for all four cases in the table above (without any changes to upload itself). In particular, it means the downloaded files round trip without change of URL in the last two cases in the table above (e.g. when uploading to a destination like `groups/test/` without any additional prefix).

> P.S. The `--dry-run` functionality was introduced at the end of July ([6ab843a](https://github.com/nextstrain/cli/commit/6ab843acc227b034049e65e86b892daeb85f5e1a)), whereas #169 was from early April.

Yep, your review helped prioritize implementing `--dry-run` earlier rather than at some nebulous later time. :-)

> A lot of my review focused on the uncertainty of what will happen in a command, which in hindsight is better _explained_ by a dry-run rather than trying to get the perfect intuitive interface (which I don't think exists).

:100: I like how you put this. I think that's spot on.

> P.P.S `aws s3 cp` uses `--dryrun`. But they also don't use `--help`. Such is life shrug

Yeaaaah. IME, `aws` is not a paragon of CLI conventions. The `--help` thing still gets me. In any case, `--dry-run` is more conventional IME, though we could accept both forms if you think it's important!

**Comment by tsibley** [comment]
I was cursorily curious and used https://cs.github.com to search for `--dry-run` vs. `--dryrun`: ~189k vs. ~15k estimated hits. And a brief scrolling thru results seems to implicate `aws` specifically in many of the latter! :upside_down_face:

**Comment by tsibley** [comment]
Closing for now as the plan is to leave behaviour as it is. We may still implement (1), the new option like `--destination-from-filename` to override single-mode, in the future.
