### ISSUE TITLE
DOC: Mention disk space requirements for managed conda-runtime and docker

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/cli#225]
Some users may be tight on disk space, so it'd be nice to mention how big our various runtimes are.

For example, managed conda seems to use about 2.4GB on my M1 mac.

Not sure how big the docker container is, maybe 600 MB?

Otherwise it could come as a surprise to people that they suddenly need to free up >2GB.

I know, SSD is cheap, but until recently I had only 256GB, and with dual boot windows actually only 150 GB so I was always short on space. If you already have a conda environment, installing nextstrain managed-conda uses up a lot of extra space, since none of the cached packages can be used.

**Comment by tsibley** [comment]
Good suggestion. I've been wanting to add better runtime documentation for a bit now, and this would be a good thing to cover in that.

**Comment by tsibley** [comment]
Resolved by https://github.com/nextstrain/cli/commit/23281d54543d84244d4f94231b932432492ca738.
