### ISSUE TITLE
ENH: Output commit hash of the workflow repo used when using repo actions to submit

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/cli#227]
I accidentally started an action just before I pushed from local to Github.

I couldn't figure out whether the action was then using the repo before or after I had pushed.

It would be nice if the repo output the commit hash of the repo when submitting through github actions.

**Comment by tsibley** [comment]
@corneliusroemer This is a bit light on details. What action did you start? Which repo? (How does this relate to the Nextstrain CLI?)

**Comment by corneliusroemer** [comment]
I guess I just didn't look properly.

I ran an ncov rebuild action, and wasn't sure which commit this was running on.

<img width="1955" alt="image" src="https://user-images.githubusercontent.com/25161793/196749560-be4eafe5-f65b-45fa-8cb5-cfbc52e29c65.png">


The info seems to be available on the action display:

<img width="1284" alt="image" src="https://user-images.githubusercontent.com/25161793/196749548-5641edfa-2b12-40c2-9ebe-698860c05902.png">
