### ISSUE TITLE
When using `--aws-batch`, the `--image` argument is ignored

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/cli#255]
### Current Behavior
When passing `--image` together with `--aws-batch`, the `--image` option is ignored. It is neither used nor is a warning emitted that this option will have no effect.

### Expected behavior
Either use the image specified by the option or warn the user that the option is not supported and ignored.

### How to reproduce
Run `nextstrain build --image nextstrain/base:build-20230217T192833Z --aws-batch .` and observe results

**Comment by joverlee521** [comment]
@corneliusroemer Is this related to the [amd64 vs arm64 issue in docker-base](https://github.com/nextstrain/docker-base/issues/128)? 

We're using the `--image` option with `--aws-batch` for our [ncov-ingest runs](https://github.com/nextstrain/docker-base/issues/128) and it definitely works as expected there.

**Comment by corneliusroemer** [comment]
Yes sorry, I should have closed this after I realized the amd arm issue was the root cause here!
