### ISSUE TITLE
Invalid `~/.shrc` file named in standalone installer instructions

### ISSUE THREAD

**Issue by tsibley** [nextstrain/cli#319]
When the default shell is `sh`, the standalone installer generates `~/.shrc` as the shell rc file to modify, which appears to be incorrect.

From @aperofsky [in Slack](https://bedfordlab.slack.com/archives/C036L7V615F/p1695705199036659):

> I have a Macbook Pro M1 Max running Ventura 13.6.
>
> At the end of the Nextstrain installation, there are the instructions: 
>
>     To make the "nextstrain" command available in your default shell (sh)
>     without using the full path, please run these two commands now:
>    
>       printf '\n%s\n' 'eval "$("/Users/.../.nextstrain/cli-standalone/nextstrain" init-shell sh)"' >> ~/.shrc
>       eval "$("/Users/.../.nextstrain/cli-standalone/nextstrain" init-shell sh)"
>    
>     The first adds a line to your shell initialization file (~/.shrc) for future
>     sessions. The second sets up your current shell session. You only need to run
>     these once.
>
> I needed to replace `~/.shrc` with `~/.profile` to get my default shell (sh) to recognize the Nextstrain command.

`sh` is probably actually `zsh` or `bash` in POSIX-compat mode. We clearly need to be using a different file, but I'm not sure if `~/.profile` is the right one as I suspect that's only used on login shells (e.g. as it is by `bash`, at least in non-POSIX-compat mode). On macOS, all shells in Terminal.app are login shells by default, but that's not true for elsewhere.

First step is to reproduce this locally on macOS and Linux. Next is to figure out the most appropriate file.

**Comment by corneliusroemer** [comment]
Off the top off my head, thinking about why someone would get `zsh` in POSIX-compat mode: maybe if one doesn't have `xcode-select` tools installed things differ from the average Nextstrain dev mac setup.

Is there a reason we currently pipe into `bash` on macOS? `zsh` would be more canonical on mac as the default bash is now very outdated.

```
$ /bin/bash --version
GNU bash, version 3.2.57(1)-release (arm64-apple-darwin22)
Copyright (C) 2007 Free Software Foundation, Inc.

$ /bin/bash
The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
bash-3.2$ 
```

**Comment by corneliusroemer** [comment]
I think a workaround may be for us to recommend users change their default shell: `$ chsh -s /bin/zsh`

That might be how to reproduce: change default shell back to `/bin/bash`.

**Comment by tsibley** [comment]
> Off the top off my head, thinking about why someone would get `zsh` in POSIX-compat mode: maybe if one doesn't have `xcode-select` tools installed things differ from the average Nextstrain dev mac setup.

I don't have macOS 13 to test on, but on 12.6.8 `/bin/sh` is linked to `/bin/bash` and thus will trigger Bash's `sh`-compat + POSIX-compat modes (which are separate, something I'd forgotten). The `sh`-compat mode explicitly doesn't read an interactive startup file (e.g. rc file). Quoting the man page:

> **\--norc**  Do not read and execute the personal initialization file *\~/.bashrc* if the shell is interactive. This option is on by default if the shell is invoked as **sh**.

and

> If **bash** is invoked with the name **sh**, it tries to mimic the startup behavior of historical versions of **sh** as closely as possible, while conforming to the POSIX standard as well. When invoked as an interactive login shell, or a non-interactive shell with the **\--login** option, it first attempts to read and execute commands from */etc/profile* and *\~/.profile*, in that order. The **\--noprofile** option may be used to inhibit this behavior. When invoked as an interactive shell with the name **sh**, **bash** looks for the variable **ENV**, expands its value if it is defined, and uses the expanded value as the name of a file to read and execute. Since a shell invoked as **sh** does not attempt to read and execute commands from any other startup files, the **\--rcfile** option has no effect. A non-interactive shell invoked with the name **sh** does not attempt to read any other startup files. When invoked as **sh**, **bash** enters *posix* mode after the startup files are read.
>
> When **bash** is started in *posix* mode, as with the **\--posix** command line option, it follows the POSIX standard for startup files. In this mode, interactive shells expand the **ENV** variable and commands are read and executed from the file whose name is the expanded value. No other startup files are read.

Would be good to know why `sh` is the default on some macOS systems.

---

> Is there a reason we currently pipe into `bash` on macOS? `zsh` would be more canonical on mac as the default bash is now very outdated.

The installer that's fetched is written for (and tested with) bash, not zsh or any other shell. It's easier to write for a single shell than for many, and bash is near-universally available. I'm well aware that the system bash on macOS is very old :-) but that's not much of a problem in practice for the installer (and we test against it).

> A workaround may be for us to recommend users change their default shell: `$ chsh -s /bin/zsh`

We could suggest this, but I don't think it's necessary. The change to our installer should be minimal.

**Comment by tsibley** [comment]
I wrote:

> We clearly need to be using a different file, but I'm not sure if `~/.profile` is the right one as I suspect that's only used on login shells (e.g. as it is by `bash`, at least in non-POSIX-compat mode). On macOS, all shells in Terminal.app are login shells by default, but that's not true for elsewhere.

and then actually looked at the installer again and realized we already assume a login shell is used on macOS:

https://github.com/nextstrain/cli/blob/4797a5fee9631e034be76377e243b7d46d220bfc/bin/standalone-installer-unix#L160-L201

So we can do the same here and just add a case for `sh` and `~/.profile`.

**Comment by tsibley** [comment]
I think this patch would do it, but will test and PR it later.

```diff
diff --git a/bin/standalone-installer-unix b/bin/standalone-installer-unix
index 08c1aaa..3c97e35 100755
--- a/bin/standalone-installer-unix
+++ b/bin/standalone-installer-unix
@@ -201,6 +201,17 @@ shell-rc() {
             esac;;
         zsh)
             echo "${ZDOTDIR:-~}/.zshrc";;
+        sh)
+            # sh, whether a historic version or bash in sh-compat mode, doesn't
+            # use any default startup file for interactive shells.  It only
+            # uses a default startup file for login shells.  We'll have to
+            # assume here that anyone using sh as their default shell will also
+            # be using login shells appropriately.  On macOS, at least, common
+            # terminal emulators spawn login shells.
+            #   -trs, 26 September 2023
+
+            # shellcheck disable=SC2088
+            echo "~/.profile";;
         *)
             # A decent guess?
             #
```
