### ISSUE TITLE
Scheduled CI failed across macOS due to IQTree error: `Invalid "-ntmax" option`

### ISSUE THREAD

**Issue by tsibley** [nextstrain/cli#372]
```
ERROR: Shell exited 2 when running: iqtree -ntmax 1 -s results/aligned-delim.fasta -m GTR -ninit 2 -n 2 -me 0.05 -nt AUTO -redo > results/aligned-delim.iqtree.log
Command output was:
  ERROR: Invalid "-ntmax" option.
```

[Failing run](https://github.com/nextstrain/cli/actions/runs/9421054382).

**Comment by tsibley** [comment]
The failures are when testing an ambient runtime set up for CI, so may be related to the IQTree version there.

**Comment by victorlin** [comment]
Looks like this resolved itself after a few days:

- ✅ [CI #1348: Scheduled](https://github.com/nextstrain/cli/actions/runs/9388816976)
- ❌ [CI #1349: Scheduled](https://github.com/nextstrain/cli/actions/runs/9405468211)
- ❌ [CI #1350: Scheduled](https://github.com/nextstrain/cli/actions/runs/9421054382)
- ❌ [CI #1351: Scheduled](https://github.com/nextstrain/cli/actions/runs/9430495161)
- ✅ [CI #1352: Scheduled](https://github.com/nextstrain/cli/actions/runs/9438398011)
