### ISSUE TITLE
Pyoxidizer currently unmaintained

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/cli#385]
We use Pyoxidizer and it's currently "in Zombie state" per the author.

See: https://gregoryszorc.com/blog/2024/03/17/my-shifting-open-source-priorities/

Community might take over though, e.g.:
- https://github.com/indygreg/PyOxidizer/issues/751

**Comment by tsibley** [comment]
Yeah, I'm aware. I figured we can keep using it as long as we can. There's no fundamental reason it should bitrot, i.e. existing versions should continue to work well into the future, but we may be limited in ability to use new Python versions beyond what's supported now, and if we run into bugs we'll be left with fixing them ourselves or doing without a fix (that said, we haven't ever run into any yet).

**Comment by tsibley** [comment]
(Frankly, I've considered rewriting Nextstrain CLI in Rust but haven't wanted to tackle that unless we have a very compelling reason. A bitrotting Pyoxidizer could be argued as a decently good reason, IMO, but its certainly not the only option.)

**Comment by tsibley** [comment]
Seeing this again now. I don't think we need to keep an issue open to track anything here. We can deal with concrete issues arising from PyOxidizer's maintenance status as they come up.
