### ISSUE TITLE
CI: deprecation warning for node 16 use in setup-miniconda v2

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/cli#386]
We're getting a lot of warnings in CI summary due to use of setup-miniconda v2

> The following actions uses Node.js version which is deprecated and will be forced to run on node20: conda-incubator/setup-miniconda@v2. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/

from: https://github.com/nextstrain/cli/actions/runs/10183163639

<img width="2021" alt="Google Chrome 2024-07-31 18 22 40" src="https://github.com/user-attachments/assets/cdecf31d-e7c1-481d-bb7e-56771c7799e1">

**Comment by genehack** [comment]
There is a [v3](https://github.com/conda-incubator/setup-miniconda/releases/tag/v3.0.0) that uses Node v20.

**Comment by corneliusroemer** [comment]
Thanks @genehack! I missed that Tom already has a PR for it: https://github.com/nextstrain/cli/pull/384
