### ISSUE TITLE
AWS batch file modified dates should be amended

### ISSUE THREAD

**Issue by trvrb** [nextstrain/cli#41]
@tsibley ---

Currently, when running `--aws-batch` files get downloaded from S3 and their timestamp reflects download time, for example:
```
Fenrir:seasonal-flu trvrb$ ls -lah results/
-rw-r--r--   1 trvrb  staff   3.7M Feb  5 13:33 aligned_cdc_h3n2_ha_3y_cell_hi.fasta
-rw-r--r--   1 trvrb  staff    44K Feb  5 13:33 aligned_cdc_h3n2_ha_3y_cell_hi.fasta.log
-rw-r--r--   1 trvrb  staff   4.0M Feb  5 13:33 aligned_cdc_h3n2_ha_3y_cell_hi.fasta.post_aligner.fasta
-rw-r--r--   1 trvrb  staff   3.7M Feb  5 13:33 aligned_cdc_h3n2_ha_3y_cell_hi.fasta.pre_aligner.fasta
-rw-r--r--   1 trvrb  staff   3.1M Feb  5 13:33 aligned_cdc_h3n2_na_3y_cell_hi.fasta
-rw-r--r--   1 trvrb  staff    44K Feb  5 13:33 aligned_cdc_h3n2_na_3y_cell_hi.fasta.log
-rw-r--r--   1 trvrb  staff   3.7M Feb  5 13:33 aligned_cdc_h3n2_na_3y_cell_hi.fasta.post_aligner.fasta
-rw-r--r--   1 trvrb  staff   3.1M Feb  5 13:33 aligned_cdc_h3n2_na_3y_cell_hi.fasta.pre_aligner.fasta
...
```

This messes with the ability to restart `snakemake` or `nextstrain build` locally as timestamps don't properly file build order. This results in Snakemake attempting to start from scratch. 

Would it be possible to make these files keep their original timestamps?

**Comment by tsibley** [comment]
This should be possible, yes.

How badly is this affecting your builds (e.g. seasonal flu)?  It'll be lower priority for me relative to other tasks unless it's a big thorn in your side.

**Comment by trvrb** [comment]
@tsibley --- It's a pretty big issue. If I do flu builds via `--aws-batch` I can't then modify our figure scripts needed for the WHO report as generating `figures/` causes the build to restart: https://github.com/nextstrain/seasonal-flu/blob/master/Snakefile_report#L34

**Comment by tsibley** [comment]
Got it. I'll look into addressing this early next week.

**Comment by tsibley** [comment]
Released in nextstrain-cli 1.9.1.

**Comment by trvrb** [comment]
Thank you @tsibley!

**Comment by trvrb** [comment]
Running flu batch jobs with this was successful. I'm able to add Snakemake targets without it getting confused.

**Comment by tsibley** [comment]
Excellent!
