### ISSUE TITLE
[check-setup] Clarify help for --set-default

### ISSUE THREAD

**Issue by alliblk** [nextstrain/cli#53]
With release 1.11.1 we can now check the computer's hardware and assess what type of nextstrain running architectures are available (docker, native, or AWS). The thing that is nice about this is that you can have the same running commands (e.g. `nextstrain build <dir>`) on both a windows machine which can't use docker and a mac or some other machine that does allow docker.

You can also set a default run type to use, using the flag `--set-default` when running `nextstrain check-setup`. Currently when `nextstrain check-setup --help` is run, the help statement describes what `set-default` does, but does not specify the rank order of running methods that it will choose from when picking a default setting. This should be amended to be more clear that first choice for default is docker, followed by native.

Putting this issue up now to remember it, but I'm unlikely to get to this until after I'm back from the DRC.

**Comment by mlarrousse** [comment]
Hi I'm looking to get started contributing - may I pick this up? I'd also like to add an option to set native or aws-batch as a default during check-setup if all environments are viable.

**Comment by tsibley** [comment]
Hi @mlarrousse, we'd be happy to have a doc patch resolving this issue!

As for adding an option to `check-setup` to explicitly specify the desired default runner, I think I'd prefer to make that part of a more general new command, `nextstrain config`, which would let you see and modify all config values. I've imagined this would work like `git config`. So far I've held off on making this command, but now might be the time. Would be best to work on that as a separate issue.

**Comment by mlarrousse** [comment]
Ok! I can file a separate issue for the config command.
