### ISSUE TITLE
[aws batch] Gracefully handle network-level errors during uploading

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/cli#75]
**Current Behavior**  

I'm getting this error frequently when running ncov builds on aws-batch -- only around 1/3 of my attempts to run the command succeed. It's related to uploading the large (400+Mb) repo which is needed to run SARS-CoV-2 builds currently. The internet is not down, so it's not the same as #55.

```
$ nextstrain build --aws-batch --detach ...
...
zipped: /Users/naboo/github/nextstrain/ncov/Snakefile_Priorities

Traceback (most recent call last):
  File "/Users/naboo/miniconda3/lib/python3.7/site-packages/urllib3/connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/Users/naboo/miniconda3/lib/python3.7/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/Users/naboo/miniconda3/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:
...
  File "/Users/naboo/miniconda3/lib/python3.7/site-packages/botocore/httpsession.py", line 283, in send
    raise EndpointConnectionError(endpoint_url=request.url, error=e)
botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: <redacted>
```

This is the nextstrain-cli function which triggers it:
```
  File "/Users/naboo/github/nextstrain/cli/nextstrain/cli/runner/aws_batch/__init__.py", line 121, in run
    remote_workdir = s3.upload_workdir(local_workdir, bucket, run_id)
  File "/Users/naboo/github/nextstrain/cli/nextstrain/cli/runner/aws_batch/s3.py", line 70, in upload_workdir
    remote_workdir.upload_fileobj(tmpfile)
```

**Expected behavior**  
Ability to upload large build directories despite less-than-ideal network upload speeds.

**Additional context**  
nextstrain.cli 1.16.5

**Comment by tsibley** [comment]
My intuition tells me this is most likely a network- or host-level problem that the CLI can't solve. We might be able to provide better messaging by catching the error, though I'm not sure yet what that message would be.

**Comment by tsibley** [comment]
Based on the OS-level error message (`socket.gaierror: [Errno 8] nodename nor servname provided, or not known`), my guess is that this is a DNS resolution issue, i.e. DNS is timing out or returning NXDOMAIN.

@jameshadfield Could you provide (in private if you wish) the redacted endpoint URL in `Could not connect to the endpoint URL: <redacted>` above? This should include the domain name which didn't resolve for you. I expect this is an AWS S3 endpoint which probably includes a bucket name.

**Comment by jameshadfield** [comment]
👍 will provide next time this happens

**Comment by tsibley** [comment]
> It's related to uploading the large (400+Mb) repo which is needed to run SARS-CoV-2 builds currently.

Hmm, do you have the sequences data downloaded locally when you launch the build? If you can start from a clean ncov repo (rather than a partial build), it should be much smaller. Mine is 57 MiB uncompressed. The build will automatically download the latest sequences, though you'll need your AWS credentials in the environment.

**Comment by jameshadfield** [comment]
> Hmm, do you have the sequences data downloaded locally when you launch the build?

Yes (and this is necessary sometimes, e.g. testing changes to the data that are not on the s3 version). Does the [localrules](https://github.com/nextstrain/ncov/blob/master/Snakefile#L46) not apply on AWS?

**Comment by tsibley** [comment]
Understood that it's sometimes necessary.

"localrules" does not apply here. The workflow runs on the Batch node directly (e.g. it is the "local" host), so Snakemake doesn't consider any remote job execution to be happening.
