### ISSUE TITLE
Add login and logout commands to support Nextstrain Groups users

### ISSUE THREAD

**Issue by tsibley** [nextstrain/cli#89]
On first use:

```
$ nextstrain login
Logging into nextstrain.org…
Username:
Password:
Logged in successfully!
Credentials saved to ~/.nextstrain/secrets.
```
or
```
Failed to log in: {error}
```

Afterwards:

```
$ nextstrain login
Logged into nextstrain.org as {username}.
Log out with `nextstrain logout`.

$ nextstrain logout
Credentials removed from ~/.nextstrain/secrets.
Logged out.

$ nextstrain login --check
Checking credentials by logging into nextstrain.org…
Logged in successfully!
```

The `nextstrain login` command would prompt for nextstrain.org credentials, verify them, and store them (or maybe some shorter-lived derived credentials?) locally for later use (e.g. by `nextstrain remote upload` in the future).

Credentials can be stored in _~/.nextstrain/secrets_ under a `[login]` section. While the [keyring](https://pypi.org/project/keyring/) package makes cross-platform secret storage easier, it comes with a bit of initial setup overhead that might make CLI installation and usage much harder.

**Comment by jameshadfield** [comment]
Looks great! I'm not too worried about needing shorter-term derived credentials, but will defer to your judgement.

**Comment by tsibley** [comment]
For authenticating directly against the Cognito User Pool, we can either use the `USERNAME_PASSWORD` authentication flow with the `boto3.client("cognito-idp").initiate_auth()` method or use the more secure (but complex) `USERNAME_SRP` authentication flow (SRP = secure remote password, a standard protocol) via the third-party library [pycognito](https://github.com/pvizeli/pycognito). The latter is the better choice as long as it and the additional Python dependencies it brings in aren't onerous on our users during installation of the CLI.

Either way, the CLI needs its own app client id registered for the user pool, so I've done that in the web console. It is `2vmc93kj4fiul8uv40uqge93m5` and currently only allows `USERNAME_PASSWORD` and `USERNAME_SRP` authentication flows.

On success, Cognito's InitiateAuth action (or a subsequent ChallengeResponse action, with SRP) returns a couple different tokens for the logged in user. Note that these are specific to Cognito and are not general AWS IAM access tokens. The access token returned can be used with various Cognito actions like, for example, GetUser via `boto3.client("cognito-idp").get_user(AccessToken = …)`.

What the login command stores in _~/.nextstrain/secrets_ is up for discussion. The minimum and easiest is username and password. Improvements to that bare minimum would be not storing the password but just the access and refresh tokens. The short-lived access token would be used by other CLI commands until it expires, at which point the refresh token is used to get new tokens. Eventually, the user would have to provide their password again.

**Comment by kairstenfay** [comment]
> The latter is the better choice as long as it and the additional Python dependencies it brings in aren't onerous on our users during installation of the CLI.

@tsibley How do we determine if a python package installation is onerous on the users? I just installed pycognito and it went smoothly on my end.

**Comment by kairstenfay** [comment]
> Credentials can be stored in _~/.nextstrain/secrets_ under a `[login]` section

Are you thinking this would be formatted as an INI file, then? Will _~/.nextstrain/secrets_ be a new file, or are other systems currently using it?

**Comment by tsibley** [comment]
Yep, an INI file of the kind configparser supports and used by `nextstrain.cli.config` for _~/.nextstrain/config_.

_~/.nextstrain/secrets_ would be a new file, to be used by subsequent additions to the CLI.

**Comment by tsibley** [comment]
> How do we determine if a python package installation is onerous on the users? I just installed pycognito and it went smoothly on my end.

Great question! There are not hard and fast rules here. A lot of evaluation "is dep X worth it?" is squishy and experience based. Two big factors that make a dep more of a cost:

- Lots of transitive dependencies (e.g. we add dep A which in turn deps on B, C, D, E, …), as each additional dep adds to install time and increases the chance of a dep causing installation issues.

- Inclusion of low-level bindings written in C instead of being pure Python. This kind of dep is much harder to install when binary packages aren't available for a platform (e.g. may be available for Linux but not macOS) since they need to be compiled from source.

**Comment by huddlej** [comment]
@tsibley Did #115 sufficiently resolve this issue?

**Comment by tsibley** [comment]
Yes, thanks for the tidying!
