### ISSUE TITLE
[update] Stop overwriting `nextstrain/base:latest` in `~/.nextstrain/config`

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/cli#96]
Running `nextstrain update` sets the `docker.image` config to the `nextstrain/base:build-*` tag even when `docker.image` is explicitly set to `nextstrain/base:latest`.

This is due to this bit of code within the [`latest_build_image()` function](https://github.com/nextstrain/cli/blob/master/nextstrain/cli/runner/docker.py):
```python
if tag == "latest" or is_build_tag(tag):
        build_tags = sorted(filter(is_build_tag, tags(repository)))

        if build_tags:
            return repository + ":" + build_tags[-1]
        else:
            return repository + ":latest"
    else:
        return image_name
```

**Comment by tsibley** [comment]
Good make sure with this that on first run, the default image still leads to a pinned `build-*` tag. I think the desired behaviour can be achieved by conditioning on implicit vs. explicit `latest` tag.
