### ISSUE TITLE
config: Perform larger refactorings

### ISSUE THREAD

**Issue by kairstenfay** [nextstrain/cli#99]
From @tsibley:
> Separate from context manager support [#98], the kind of larger refactoring I'm thinking of is having `nextstrain.cli.config` and `nextstrain.cli.secrets` [created in #92] which both use the same underlying code, but point to different default files.
> (which might be done by creating a `nextstrain.cli.config.ConfigFile` class that is subclassed by a `nextstrain.cli.secrets.SecretsFile` class, or something)

**Comment by tsibley** [comment]
No longer applicable.
